#!/usr/bin/env bash
# Bash script to install nginx web server

sudo apt-get update -y
sudo apt-get install nginx -y
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
sudo service nginx start
