#!/usr/bin/env bash
# Bash script to install nginx web server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
eho "Hello World!" > /var/www/html/test_page.html
sudo service nginx start
