#!/usr/bin/env bash
# Bash script to Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' > /var/www/html/index.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
   
    root /var/www/html;
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
}"
 > default

sudo mv -f default /etc/nginx/sites-available/default

sudo service nginx restart
