#!/usr/bin/env bash
# Bash script that tries to print "to infine and beyond" infinitely but ultimately fails

echo "$$" > /var/run/myscript.pid

fsigterm () {
    echo "I hate the kill command"
    rm /var/run/myscript.pid
    exit 1
}

fsigint () {
    echo "Y U no love me?!"
    rm /var/run/myscript.pid
    exit 1
}

fsigquit () {
    rm /var/run/myscript.pid
    exit 1
}
 
while true; do
    echo "To infinity and beyond"
    sleep 2
    trap fsigterm SIGTERM
    trap fsigint SIGINT
    trap fsigquit SIGQUIT
done
