#!/usr/bin/env bash
# This script is the invincible version of the 4-to_infinity_and_beyond script

invincible() {
    echo "I am invincible!!!"
}

while true; do
    echo "To infinity and beyond"
    sleep 2
    trap invincible SIGTERM
done
