#!/usr/bin/env bash
# This script is implementing fizzbuzz

# Function to check if a number is divisible by another number
is_divisible() {
    if (( "$1" % "$2" == 0 )); then
        return 0
    else
        return 1
    fi
}

# Main FizzBuzz logic
for ((i = 1; i <= 100; i++)); do
    if is_divisible "$i" 15; then
        echo "FizzBuzz"
    elif is_divisible "$i" 3; then
        echo "Fizz"
    elif is_divisible "$i" 5; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
